namespace Zamboni11.Components.NHL11.Structs;

public enum CardState : byte
{
    //TODO
    ZERO = 0,
    ONE = 1,
    TWO = 2,
    CARDHOUSE_CARDSTATE_ACTIVE_BADGE = 100,
    CARDHOUSE_CARDSTATE_ACTIVE_HOME_KIT = 101,
    CARDHOUSE_CARDSTATE_ACTIVE_AWAY_KIT = 102,
    CARDHOUSE_CARDSTATE_ACTIVE_STADIUM = 104,
    CADHOUSE_CARDSTATE_MAXIMUM_STATE = 254,
    CARDHOUSE_CARDSTATE_SEARCH_ACTIVE = 255
}