namespace Zamboni11.Components.NHL11.Structs;

public enum SeasonState : int
{
    SEASONALPLAY_SEASON_STATE_NONE = 0,
    SEASONALPLAY_SEASON_STATE_REGULARSEASON = 1,
    SEASONALPLAY_SEASON_STATE_PLAYOFF = 2,
    SEASONALPLAY_SEASON_STATE_BLACKOUT = 3
}