namespace Zamboni11.Components.NHL11.Structs;

public enum STAT : int
{
    ZERO = 0,
    ONE = 1,
    TWO = 2,
    CARDHOUSE_CARDSTATE_INVALID = 242, //UNSURE ABOUT THESE IDS: 255 is sure.
    CARDHOUSE_CARDSTATE_FREE = 243,
    CARDHOUSE_CARDSTATE_INGAME = 244,
    CARDHOUSE_CARDSTATE_INCARDSELL = 245,
    CARDHOUSE_CARDSTATE_ONLINESWAP = 246,
    CARDHOUSE_CARDSTATE_IMPROVEDSALE = 247,      
    CARDHOUSE_CARDSTATE_PARTOFOFFER = 248,
    CARDHOUSE_CARDSTATE_ACTIVE_BADGE = 249,
    CARDHOUSE_CARDSTATE_ACTIVE_HOME_KIT = 250,
    CARDHOUSE_CARDSTATE_ACTIVE_AWAY_KIT = 251,
    CARDHOUSE_CARDSTATE_ACTIVE_BALL = 252,
    CARDHOUSE_CARDSTATE_ACTIVE_STADIUM = 253,
    CADHOUSE_CARDSTATE_MAXIMUM_STATE = 254,
    CARDHOUSE_CARDSTATE_SEARCH_ACTIVE = 255
}